name: CI
on:
  push:
    paths:
      - "client/**"
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: "14.x"

    - name: Install modules
      run: yarn install

    - name: Run lint
      run: yarn lint:client

    - name: Run tests
      run: yarn test:client --ci
