name: test:server
on: push
jobs:
  server:
    name: "server"
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: "14.x"

    - uses: actions/cache@v1
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Install modules
      run: yarn install --frozen-lockfile

    - name: Run lint
      run: yarn server:lint

    - name: Run tests
      run: yarn server:test --ci
